import { ParcelStatus } from '@prisma/client';
import { TransitionDefinition, TransitionEvent } from './state-machine.types';

const DEFAULT_MAX_RETRY = 3;

/**
 * Bảng chuyển trạng thái đầy đủ — sao chép chính xác từ m3.md mục 2.2 "Transition table đầy đủ".
 * Mỗi dòng ở đây tương ứng với đúng 1 dòng trong bảng transition table đã thiết kế ở Tuần 1.
 */
export const TRANSITION_TABLE: TransitionDefinition[] = [
  {
    id: 1,
    from: null,
    to: ParcelStatus.CREATED,
    event: TransitionEvent.CREATE_PARCEL,
    allowedActors: ['customer'],
    guardDescription: 'Thông tin đơn hợp lệ',
    sideEffect: "Sinh tracking_code; ghi parcel_status_history",
    guard: () => true, // validate dữ liệu đơn nằm ở DTO của ParcelsModule (M2), không thuộc state machine
  },
  {
    id: 2,
    from: ParcelStatus.CREATED,
    to: ParcelStatus.PENDING_PICKUP,
    event: TransitionEvent.ASSIGN_COURIER,
    allowedActors: ['dispatcher', 'system'],
    guardDescription: 'Có shipper khả dụng',
    sideEffect: "Tạo delivery_assignments (status=assigned)",
    guard: (ctx) => ctx.hasAvailableCourier === true,
  },
  {
    id: 3,
    from: ParcelStatus.CREATED,
    to: ParcelStatus.CANCELLED,
    event: TransitionEvent.CANCEL_ORDER,
    allowedActors: ['customer'],
    guardDescription: 'Chưa được assign',
    sideEffect: 'Ghi lý do hủy',
    guard: () => true, // ở CREATED thì chắc chắn chưa assign
  },
  {
    id: 4,
    from: ParcelStatus.PENDING_PICKUP,
    to: ParcelStatus.PICKED_UP,
    event: TransitionEvent.CONFIRM_PICKUP,
    allowedActors: ['shipper'],
    guardDescription: 'Shipper đúng người được assign',
    sideEffect: 'Cập nhật delivery_assignments.status=in_progress',
    guard: (ctx) => ctx.isAssignedCourier === true,
  },
  {
    id: 5,
    from: ParcelStatus.PENDING_PICKUP,
    to: ParcelStatus.CANCELLED,
    event: TransitionEvent.CANCEL_ORDER,
    allowedActors: ['customer'],
    guardDescription: 'Chưa lấy hàng',
    sideEffect: 'Hủy delivery_assignments liên quan',
    guard: () => true, // ở PENDING_PICKUP thì chắc chắn chưa lấy hàng
  },
  {
    id: 6,
    from: ParcelStatus.PICKED_UP,
    to: ParcelStatus.IN_TRANSIT,
    event: TransitionEvent.DEPART_TO_HUB,
    allowedActors: ['shipper', 'system'],
    guardDescription: '—',
    sideEffect: 'Cập nhật current_location_id',
    guard: () => true,
  },
  {
    id: 7,
    from: ParcelStatus.IN_TRANSIT,
    to: ParcelStatus.AT_HUB,
    event: TransitionEvent.ARRIVE_AT_HUB,
    allowedActors: ['warehouse_staff'],
    guardDescription: "Quét tại location loại 'hub'",
    sideEffect: 'Cập nhật current_location_id, ghi lịch sử',
    guard: (ctx) => ctx.isHubLocation === true,
  },
  {
    id: 8,
    from: ParcelStatus.IN_TRANSIT,
    to: ParcelStatus.LOST,
    event: TransitionEvent.SLA_TIMEOUT,
    allowedActors: ['system'],
    guardDescription: 'Không có cập nhật > ngưỡng SLA (72 giờ)',
    sideEffect: 'Mở ticket khiếu nại',
    guard: (ctx) => (ctx.hoursSinceLastUpdate ?? 0) > 72,
  },
  {
    id: 9,
    from: ParcelStatus.AT_HUB,
    to: ParcelStatus.IN_TRANSIT,
    event: TransitionEvent.DISPATCH_TO_NEXT_HUB,
    allowedActors: ['warehouse_staff'],
    guardDescription: 'Chưa đến hub cuối',
    sideEffect: 'Cập nhật current_location_id đích tiếp theo',
    guard: (ctx) => ctx.isFinalHub === false,
  },
  {
    id: 10,
    from: ParcelStatus.AT_HUB,
    to: ParcelStatus.OUT_FOR_DELIVERY,
    event: TransitionEvent.DISPATCH_LAST_MILE,
    allowedActors: ['dispatcher'],
    guardDescription: 'Đến hub phụ trách khu vực giao',
    sideEffect: "Tạo delivery_assignments (loại last-mile)",
    guard: (ctx) => ctx.isFinalHub === true,
  },
  {
    id: 11,
    from: ParcelStatus.AT_HUB,
    to: ParcelStatus.LOST,
    event: TransitionEvent.SLA_TIMEOUT,
    allowedActors: ['system'],
    guardDescription: 'Không có cập nhật > ngưỡng SLA (72 giờ)',
    sideEffect: 'Mở ticket khiếu nại',
    guard: (ctx) => (ctx.hoursSinceLastUpdate ?? 0) > 72,
  },
  {
    id: 12,
    from: ParcelStatus.OUT_FOR_DELIVERY,
    to: ParcelStatus.DELIVERED,
    event: TransitionEvent.CONFIRM_DELIVERY,
    allowedActors: ['shipper'],
    guardDescription: 'Có bằng chứng giao (ảnh/chữ ký)',
    sideEffect: 'delivery_assignments.status=completed; thông báo customer',
    guard: (ctx) => ctx.hasDeliveryProof === true,
  },
  {
    id: 13,
    from: ParcelStatus.OUT_FOR_DELIVERY,
    to: ParcelStatus.DELIVERY_FAILED,
    event: TransitionEvent.REPORT_FAILED_DELIVERY,
    allowedActors: ['shipper'],
    guardDescription: '—',
    sideEffect: 'Ghi lý do thất bại, tăng failed_attempt_count',
    guard: () => true,
  },
  {
    id: 14,
    from: ParcelStatus.DELIVERY_FAILED,
    to: ParcelStatus.OUT_FOR_DELIVERY,
    event: TransitionEvent.RETRY_DELIVERY,
    allowedActors: ['system'],
    guardDescription: 'failed_attempt_count < max (mặc định 3)',
    sideEffect: 'Lên lịch giao lại',
    guard: (ctx) => (ctx.failedAttemptCount ?? 0) < (ctx.maxRetryAttempts ?? DEFAULT_MAX_RETRY),
  },
  {
    id: 15,
    from: ParcelStatus.DELIVERY_FAILED,
    to: ParcelStatus.RETURNING,
    event: TransitionEvent.MAX_RETRIES_REACHED,
    allowedActors: ['system'],
    guardDescription: 'failed_attempt_count >= max',
    sideEffect: 'Thông báo customer về việc hoàn trả',
    guard: (ctx) => (ctx.failedAttemptCount ?? 0) >= (ctx.maxRetryAttempts ?? DEFAULT_MAX_RETRY),
  },
  {
    id: 16,
    from: ParcelStatus.RETURNING,
    to: ParcelStatus.RETURNED,
    event: TransitionEvent.CONFIRM_RETURN_TO_SENDER,
    allowedActors: ['shipper'],
    guardDescription: 'Đã giao lại cho sender',
    sideEffect: 'Đóng mọi delivery_assignments còn mở',
    guard: () => true,
  },
];

// Các trạng thái cuối (terminal states) — không có transition đi ra, đúng theo ghi chú m3.md mục 2.2
export const TERMINAL_STATES: ParcelStatus[] = [
  ParcelStatus.DELIVERED,
  ParcelStatus.CANCELLED,
  ParcelStatus.RETURNED,
  ParcelStatus.LOST,
];
